version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: mi_postgres
    environment:
      POSTGRES_USER: Super
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: vaso_de_leche
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - red_postgres

volumes:
  postgres_data:

networks:
  red_postgres:
    driver: bridge